foods/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace foods.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your application description page.";
        }
    }
}

foods/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace foods.Pages
{
    public class ContactModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your contact page.";
        }
    }
}

foods/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace foods.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

foods/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace foods.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

foods/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace foods.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

foods/Pages/Restaurants/ClientRestaurant.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace foods.Pages
{
    public class ClientRestaurantModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

foods/Pages/Restaurants/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using foods.core;
using foods.data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace foods.Pages
{
    public class DeleteModel : PageModel
    {
        private readonly IRestaurantData restaurantData;

        public Restaurant Restaurant { get; set; }

        public DeleteModel(IRestaurantData restaurantData)
        {
            this.restaurantData = restaurantData;

        }
        public IActionResult OnGet(int id)
        {
            Restaurant = restaurantData.GetById(id);

            if(Restaurant == null){
                RedirectToPage("/NotFound");
            }
            return Page();



        }


        public IActionResult OnPost(int id)
        {
            var restaurant = restaurantData.Delete(id);
            restaurantData.commit();

            if(restaurant == null){
                RedirectToPage("./NotFound");
            }
            TempData["Message"] = $" {restaurant.Name} Deleted !";
            return RedirectToPage("./List");

        }
    }
}

foods/Pages/Restaurants/Detail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using foods.core;
using foods.data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace foods.Pages
{
    public class DetailModel : PageModel
    {
        private IRestaurantData restaurantData;

        public Restaurant Restaurant { get; set; }


        [TempData]
        public string  Message { get; set; }

        public DetailModel(IRestaurantData restaurantData)
        {
            this.restaurantData = restaurantData;
        }
        public IActionResult OnGet(int id)
        {

            Restaurant = restaurantData.GetById(id);
            if(Restaurant == null)
            {
                return RedirectToPage("./NotFound");
            }
            return Page();
        }
    }
}

foods/Pages/Restaurants/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using foods.core;
using foods.data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace foods.Pages
{
    public class EditModel : PageModel
    {
        private readonly IRestaurantData restaurantData;
        private readonly IHtmlHelper htmlHelper;
        [BindProperty]
        public Restaurant Restaurant { get; set; }
        public IEnumerable<SelectListItem> Cuisines { get; set; }

        public EditModel(IRestaurantData restaurantData, IHtmlHelper htmlHelper)
        {
            this.restaurantData = restaurantData;
            this.htmlHelper = htmlHelper;
        }
        public IActionResult OnGet(int? id)
        {
            if (id.HasValue)
            {
                Restaurant = restaurantData.GetById(id);
            }
            else
            {
                Restaurant = new Restaurant();
            }
            Cuisines = htmlHelper.GetEnumSelectList<CuisineType>();

            if (Restaurant == null)
            {
                return RedirectToPage("./NotFound");
            }

            return Page();

        }


        public IActionResult OnPost()
        {

            if (!ModelState.IsValid)
            {
             Cuisines = htmlHelper.GetEnumSelectList<CuisineType>();
              return Page();
            }

            if(Restaurant.Id > 0)
            {
               Restaurant = restaurantData.Update(Restaurant);
            }
            else{
                 Restaurant = restaurantData.Create(Restaurant);
            }
               
                restaurantData.commit();
                //pagePath , routesValues
                TempData["Message"] = "Restaurant Saved!";
                return RedirectToPage("./Detail", new { id = Restaurant.Id });

            }
           
    }






}

foods/Pages/Restaurants/List.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using foods.data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using foods.core;
using Microsoft.Extensions.Logging;

namespace foods.Pages
{
    public class ListModel : PageModel
    {
        private readonly IConfiguration config;
        private readonly IRestaurantData data;
        private readonly ILogger log;

        public ListModel(IConfiguration config, IRestaurantData data, ILogger<ListModel> log)
        {
            this.config = config;
            this.data = data;
            this.log = log;

        }
       
        public string Message { get; set; }
        public IEnumerable<Restaurant> Restaurants;


        [BindProperty(SupportsGet = true)]
        public string SearchTerm { get; set; }


        public void OnGet()
        {

            log.LogError(config["Message"]);
            Message = config["Message"];
            Restaurants = this.data.GetRestaurantsByName(SearchTerm);

        }
    }
}

foods/ViewComponents/RestaurantCountViewComponent.cs
using foods.data;
using Microsoft.AspNetCore.Mvc;

namespace foods.ViewComponents
{
    public class RestaurantCountViewComponent:ViewComponent
    {
        private IRestaurantData restaurantData;

        public RestaurantCountViewComponent(IRestaurantData restaurantData)
        {

            this.restaurantData = restaurantData;
            
        }
        

        public IViewComponentResult Invoke(){

            var  count = restaurantData.GetRestaurantsCount();

            return View(count);

        }
}
}

foods/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<p>Use this area to provide additional information.</p>

foods/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

foods/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core Razor Pages</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?linkid=852130">Working with Razor Pages.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure App Service</a></li>
        </ul>
    </div>
</div>

foods/Pages/Restaurants/ClientRestaurant.cshtml
@page
@model ClientRestaurantModel
@{

}

<h2> Client Restuarants </h2>

<table  class="table" id="tableId"> 


</table>


@section Scripts {

<environment include="Development">
    <!--
    <script src="~\node_modules\datatables.net\js\jquery.dataTables.js" ></script>
    <script src="~\node_modules\datatables.net-bs\js\dataTables.bootstrap.js"></script>
    <link rel="stylesheet" href="~\node_modules\datatables.net-bs\css\dataTables.bootstrap.css">
    -->
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/dt-1.10.20/datatables.min.css"/>
<script type="text/javascript" src="https://cdn.datatables.net/v/bs/dt-1.10.20/datatables.min.js"></script>
</environment>

<environment  exclude="Development">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/dt-1.10.20/datatables.min.css"/>
<script type="text/javascript" src="https://cdn.datatables.net/v/bs/dt-1.10.20/datatables.min.js"></script>
</environment>


    <script>

        $(function (){
            $.ajax("/api/restaurant",{method:"get"})
            .then(function(res){
                $("#tableId").dataTable({
                    data:res,
                    columns:[
                    {
                        "data":"name"
                    },
                     {
                        "data":"location"
                    },
                     {
                        "data":"cuisine"
                    },

                    ]

                });
                 
            })

        });


    </script>
}

foods/Pages/Restaurants/Delete.cshtml
@page "{id:int?}"
@model DeleteModel
@{
}

<!DOCTYPE html>


    <h2>  Delete </h2>

    <div class="alert alert-danger">

        Are you sure you want to delete @Model.Restaurant.Name ?
    </div>

    <form method="post">
        <button type="submit" class="btn btn-danger">Yes!</button>
        <a asp-page="List" class="btn btn-default">Cancel </a>

    </form>

foods/Pages/Restaurants/Detail.cshtml
@page "{id:int}"
@model DetailModel
@{
}


<h2> @Model.Restaurant.Name</h2>


@if(Model.Message != null){
    <div class="alert alert-info"> @Model.Message  </div>
}


<div>

    Id : @Model.Restaurant.Id
</div>


<div>

    Location : @Model.Restaurant.Location
</div>

<div>

    Cuisine : @Model.Restaurant.Cuisine
</div>


<a asp-page="./List" class="btn btn-default">All Restaurants </a>

foods/Pages/Restaurants/Edit.cshtml
@page  "{id:int?}"
@model EditModel
@{
}


<h1>  @Model.Restaurant.Name</h1>


<form method="post">
  <input type="hidden" asp-for="Restaurant.Id" />

  <div class"form-group">
      <label asp-for="Restaurant.Name"></label>
      <input asp-for="Restaurant.Name" class="form-control" />
      <span class="text-danger" asp-validation-for="Restaurant.Name"></span>
  </div>

   <div class"form-group">
      <label asp-for="Restaurant.Location"></label>
      <input asp-for="Restaurant.Location" class="form-control" />
      <span class="text-danger" asp-validation-for="Restaurant.Location"></span>
  </div>

  <div class"form-group">
      <label asp-for="Restaurant.Cuisine"></label>
      <select asp-for="Restaurant.Cuisine" class="form-control"
        asp-items="Model.Cuisines"
       >

        
      </select>
      <span class="text-danger" asp-validation-for="Restaurant.Cuisine"></span>
  </div>




   <button type="submit" class="btn btn-success">Save</button>
</form>


@section scripts {

    <partial name="_ValidationScriptsPartial" />
}

foods/Pages/Restaurants/List.cshtml
@page
@model ListModel
@{
}


<h1> Restaurants </h1>


<form method="get">
<div class="form-group">
<div class="input-group">

    <input asp-for="SearchTerm" type="search" class="form-control" />
    <span class="input-group-btn">

        <button class="btn btn-default">
            <i class="glyphicon glyphicon-search" ></i>
        </button>
    </span>

</div>

</div>


</form>


@foreach (var r in Model.Restaurants){

    <partial name="_Summary" model="r" />
}


<a asp-page="./Edit"  class='btn-btn-info' > Add New</a>



@section footer{
    <div>

 @Model.Message  

</div>

}

foods/Pages/Restaurants/NotFound.cshtml
@page
@{ 
}
    

<h1> Page Not Found !</h1>

<a asp-page="./List"  class="btn btn-primary"> See all Restaurants !</a>

foods/Pages/Restaurants/_Summary.cshtml
@using foods.core
@model Restaurant

<div class="panel panel-default">

<div class="panel-heading">
    <h3> @Model.Name</h3>
</div>

<div class="panel-body">

    <span> Location : @Model.Location</span>
     <span> Cuisine  : @Model.Cuisine</span>
</div>

<div class="panel-footer">
         <a class="btn btn-lg"
           asp-page="./Detail"
           asp-route-id="@Model.Id"
           >
          <i class="glyphicon glyphicon-zoom-in" ></i>

          </a>

            <a class="btn btn-lg"
             asp-page="./Edit"
             asp-route-id="@Model.Id"
           >  
          <i class="glyphicon glyphicon-edit" ></i>

          </a>
            <a class="btn btn-lg"
             asp-page="./Delete"
             asp-route-id="@Model.Id"
           >  
          <i class="glyphicon glyphicon-trash" ></i>

          </a>

</div>

</div>

foods/Pages/Shared/Components/RestaurantCount/Default.cshtml
@model int

<div class="well">

    there are @Model restaurants here .
    <a asp-page="/Restaurants/List">
    See them all
    </a>
</div>

foods/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - foods</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-page="/Index" class="navbar-brand">foods</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-page="/Index">Home</a></li>
                    <li><a asp-page="/About">About</a></li>
                    <li><a asp-page="/Contact">Contact</a></li>
                     <li><a asp-page="/Restaurants/List">Restaurants</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <vc:restaurant-count></vc:restaurant-count>
            @RenderSection("footer", required: false)
            <p>&copy; 2020 - foods</p>
        </footer>
        
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>